import LocalizedStrings from 'react-native-localization';

const Strings = new LocalizedStrings({
    ar: {
        addChat: 'إضافه محادثه',
        startChat: 'إبدأ محادثه',
        noChatsYet: 'لا يوجد محادثات ',
        reload: 'إعاده التحميل',
        message: 'رسالتك...',
        userName: 'اسم المستخدم',
        userBio: 'جمله تعبر عنك',
        update: 'تعديل',
        noPostsYet: 'لا توجد منشورات ..',
        writeToYourBio: 'اكتب جمله تعبر عنك',
        Posts: 'المنشورات',
        post: 'نشر',
        createNewAccount: 'إنشاء حساب جديد',
        whatsInYourMind: 'اكتب منشور ...',
        userEmail: 'البريد الالكتروني',
        completeRegisterationSuccessfully: 'تم اكمال بيانات التسجيل بنجاح',
        required: 'مطلوب',
        passwordValidation: "يجب ان تحتوى كلمه المرور على 4 حروف على الاقل ",
        passwordsMatch: "كلمتى المرور غير متطابقه",
        userFullName: 'اسم المستخدم',
        password: ' كلمه المرور',
        confirmPassword: 'تأكيد كلمه المرور ',
        login: 'تسجيل الدخول',
        termsAndConditions: 'الموافقه علي الشروط والأحكام الخاصه بالتطبيق',
        confirm: 'تأكيد',
        save: 'حفظ',
        haveAccount: 'لديك حساب ؟..تسجيل الدخول',
        accountCreatedSuccessfully: "تم التسجيل بنجاح",
        signUp: 'تسجيل الدخول',
        delete: 'مسح',
        close: 'إلغاء',
        loginSuccessfully: "تم التسجيل بنجاح",
        done: 'تم',
        cancel: 'الغاء',
        openCamera: 'ألتقط من الكاميرا',
        openGallery: 'أختر من الجاليري',
        termsAndConditionsTitle: 'الشروط والأحكام',
        socialApp: 'Social App',
        forgetPassword: 'نسيت كلمه المرور',
        loginFB: 'تسجيل الدخول بواسطه الفيسبوك',
        loginGM: 'تسجيل الدخول بواسطه جوجل',
        addPost: 'إضافه منشور',
        addImgToPost: 'أضف صوره للمنشور'
    },
    en: {
        message: 'Message...',
        userBio: 'userBio',
        userName: 'userName',
        update: 'Update',
        post: 'Post',
        Posts: 'Posts',
        noPostsYet: 'No posts yet !',
        addPost: 'Add Post',
        whatsInYourMind: "Write a post ...",
        writeToYourBio: 'Write to your bio ..',
        userEmail: 'Email',
        completeRegisterationSuccessfully: 'Registeration data completed successfully',
        required: 'required',
        passwordValidation: 'Password must have at least 4 characters ',
        passwordsMatch: 'Passwords must match ',
        userFullName: 'Full name',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        login: 'Login',
        createNewAccount: 'Create new account',
        termsAndConditions: 'Accept app terms and conditions',
        confirm: 'Confirm',
        save: 'Save',
        accountCreatedSuccessfully: ' Account created Succssfully ',
        signUp: 'Sign Up',
        delete: 'Delete',
        close: 'Close',
        loginSuccessfully: ' Login Succssfully ',
        done: 'Done',
        cancel: 'Cancel',
        openCamera: 'Open Camera',
        openGallery: 'Open Gallery',
        termsAndConditionsTitle: 'Terms and conditions',
        socialApp: 'Social App',
        forgetPassword: 'Forget Password?',
        loginFB: 'Sign In With Facebook',
        loginGM: 'Sign In With Google',
        haveAccount: 'Have an Account?..Sign In',
        addImgToPost: 'Add image to post',
        reload: 'Reload',
        noChatsYet: 'No Chats Yet',
        startChat: 'Start Chat',
        addChat: 'Add Chat'
    }

});

export default Strings